# Generated by Django 3.1.1 on 2020-09-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('SOLD', 'Item already purchased'), ('AVAILABLE', 'Item ready to be purchased'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('SOLD', 'Item already purchased'), ('AVAILABLE', 'Item ready to be purchased'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('SOLD', 'Item already purchased'), ('AVAILABLE', 'Item ready to be purchased'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=10),
        ),
    ]
